project:
  type: website

website:
  title: "Wiki Lis"


  navbar:
    background: secondary
    style: "floating"
    search: true
    right:
      - text: Home
        file: index.qmd
      - text: about 
        file: about.qmd
      - sidebar:java
      - text: Vocabulary
        file: vocabulary/vocabulary.qmd

  
  sidebar:
    - id: "java"
      title: "Java SE" 
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "Java"
        - text: "---"  
        - section: "Java: concepts"
          contents: 
            - java/java.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true