
project:
  type: website


website:
  title: Wiki Lis
  #cookie-consent:
  #  type: express
  #  style: headline
  #  palette: purple

  
  repo-url: https://github.com/Lisdev90
  repo-actions: [edit, issue]

  navbar:
    background: teal
    style: "floating"
    search: true
          
    left:
      - text: Home
        menu:
        - about.qmd
        - java/java.qmd
        - react/react.qmd
        - scrum/scrum.qmd
        - quarto/quarto.qmd
        - vocabulary/vocabulary.qmd                
  
  
  page-footer: 
    background: teal
    left: "[Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)" 
    center: "¡Hello World!" 


format:
  html:
    fontsize:  "1.0em"
    theme:
      light: pulse
      dark: solar
    css: styles.css
    toc: true
    toc-depth: 5
    email-obfuscation: javascript
    
execute:
  cache: true
  freeze: true