project:
  type: website

website:
  title: "Wiki Lis"


  navbar:
    background: purple
    style: "floating"
    search: true
    left:
      - text: Home
        menu:
        - about.qmd
        - java/java.qmd
        - react/react.qmd
        - scrum/scrum.qmd
        - quarto/quarto.qmd
        - vocabulary/vocabulary.qmd


  sidebar:
    - id: "java"
      title: "Java SE" 
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "Java"
        - text: "---"  
        - section: "Java: concepts"
          contents: 
            - java/java.qmd


    - id: "react"
      title: "React JS" 
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "React"
        - text: "---"  
        - section: "React: concepts"
          contents: 
            - react/react.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true